### ISSUE TITLE
Allow custom curve implementation module

### ISSUE THREAD

**Issue by pma** [zeromq/chumak#10]
Hi,

I was trying to use chumak and Kcl project (https://hex.pm/packages/kcl) from Elixir to have a completely NIF-free solution, but currently it's not easy to provide your own NaCl compatible module without changing the library.

What do you think of making the interface exposed by `chumak_curve_if` a behaviour and letting the application provide a custom implementation module at configuration time, or as an optional parameter when instantiating a socket?

**Comment by drozzy** [comment]
I'm currently seeking any and all suggestions, as I don't use the crypto myself in production. It would be best to have someone who uses it live to suggest for a way of going forward. The current implementation was merely a push to get people to contribute.

Feel free to submit your suggestion as a PR, it will be merged.

**Comment by drozzy** [comment]
Closing this until someone decides to work on it. Feel free to re-open or make a new PR directly.

Currently I don't have time to work on this myself (nor the knowledge).
