### ISSUE TITLE
Is socket thread(process) safe?

### ISSUE THREAD

**Issue by larrymeng** [zeromq/chumak#26]
Is it safe to share the same connection? (call from 2 or more erlang processes.)

Thanks,

**Comment by drozzy** [comment]
Yes, socket is a gen_server, so any "calls" you make to it just get converted to messages in a mailbox:

https://github.com/zeromq/chumak/blob/master/src/chumak_socket.erl

**Comment by drozzy** [comment]
Closing, feel free to re-open if this is still an issue.
