### ISSUE TITLE
Silence :connection_error

### ISSUE THREAD

**Issue by micahrye** [zeromq/chumak#28]
Is it possible to silence :connection_error messages? 

In my case I am using Chumak via Elixir. In the application I am using a push socket, but the socket to connect to (pull) may not have bound yet etc. 

When the pull socket is not bound I get a done of `[{:host, 'localhost'}, {:port, 3400}, :connection_error, {:error, :econnrefused}]` in the console when developing or in logs. 

Example code:

```elixir
socket_port = 3400
{:ok, socket} = :chumak.socket(:push, 'pushid')
:chumak.connect(socket, :tcp, 'localhost', socket_port)
```

**Comment by micahrye** [comment]
While the [following](https://elixirforum.com/t/addition-of-erlang-dep-causing-sasl-logging/9265) does not solve this issue, it shows how others have turned off logging from a Erlang dependency. In the case of the link: 

```
config :sasl, :sasl_error_logger :false
```

For an application that use SASL. 

There is also this [thread](https://github.com/elixir-lang/elixir/issues/6064), but still have not found the answer, though I have learned a bit.

Probably not related but for the config :sasl I have seen the following three different configs discussed: 

```
config :sasl, :sasl_error_logger, false
config :sasl, sasl_error_logger: false
config :sasl, sasl_error_logger: :false
```

**Comment by drozzy** [comment]
The error is generated here:

https://github.com/zeromq/chumak/blob/88cfb85ab4aa0f1b9a2a8607f16b2b433b6b9c37/src/chumak_peer.erl#L275

Is the error not correct?
Regarding silencing the logs, see here:
http://erlang.org/doc/man/error_logger.html#error_report-1 and http://erlang.org/doc/system_principles/error_logging.html

Let me know if this helps or not.

**Comment by drozzy** [comment]
Try erlang slack, they are very smart there:

Get invite:
https://erlang-slack.herokuapp.com

Join:
https://erlanger.slack.com/messages

They will also help with Elixir.

**Comment by drozzy** [comment]
Please let us know if you fixed the issue. I’m going to close this - reopen it if you still have a problem.
