### ISSUE TITLE
Delivery feedback when sending multipart message?

### ISSUE THREAD

**Issue by an0nym05** [zeromq/chumak#55]
Hi,

I'm using the library in a simple implementation of the 7/MDP protocol (https://rfc.zeromq.org/spec/7/) and using ROUTER/DEALER sockets combination. 
The issue I'm experiencing is when client is disconnected - is there a way to monitor for disconnect knowing the identity?
Relying on MDP heartbeats also doesn't help as `:chumak.send_multipart/2` always returns `:ok`, also for disconnected parties.

Thank you in advance!

**Comment by drozzy** [comment]
Hey,
If you want to submit PR I would be happy to merge it👏
