### ISSUE TITLE
Release on hex.pm

### ISSUE THREAD

**Issue by pavels** [zeromq/chumak#57]
Can i kindly ask for new release on hex.pm? There are some changes accumulated in the repo, it would be awesome to have new version on hex.pm.

**Comment by drozzy** [comment]
Will do.

I really should figure out how to do this automatically via github actions on some major/minor version change. Do you have any experience with that?

**Comment by pavels** [comment]
Thanks

Unfortunately i have no experience with rebar  - i am more of an Elixir guy, so have experience with `mix` but not with rebar.

But looks like it is not hard - https://github.com/erlangpack/github-action - you just need to create file named `.github/workflows/rebar-publish.yml` in your repository with the mentioned content, add the API Key and you should be good to go

**Comment by drozzy** [comment]
Thanks that worked.
Now when you want a new version simply bump the erlang version here and send a PR and it will push a new Hex.pm package with that version.
