### ISSUE TITLE
OTP examples

### ISSUE THREAD

**Issue by heri16** [zeromq/chumak#6]
Provide examples as OTP GenServer or alike.

**Comment by drozzy** [comment]
@heri16 do you mean using it as GenServer?
Have you looked at the [examples](https://github.com/chovencorp/chumak/tree/master/examples) dir?

Are you having trouble with something in particular? Please post your code (even if incomplete).

If you mean something else, let me know.

**Comment by drozzy** [comment]
Closing this in favor of general examples bug:
https://github.com/zeromq/chumak/issues/11

Once that is implemented, there will be plenty of examples on how to get this running.
